In [1]:
#Import
import pandas as pd

Read data

In [2]:
data = pd.read_csv('IMDB.csv')
training_data = data.head(40000)
test_data = data.tail(10000)

In [3]:


training_data.describe().round(1)

                                                   review sentiment
count                                               40000     40000
unique                                              39734         2
top     Loved today's show!!! It was a variety and not...  negative
freq                                                    5     20007

# "SPOILER" in text

In [4]:

rewiev_spoiler_index = training_data["review"].str.find("spoilers")
#rewiev_spoiler = rewiev_spoiler.sort_values()
rewiev_spoiler = pd.DataFrame( columns=['id', 'review'])

for index, value in rewiev_spoiler_index.items():
    if value != -1 :
        if training_data.iat[index,0].find("any spoiler") == -1 and  training_data.iat[index,0].find("no spoiler") == -1 :
            rewiev_spoiler = rewiev_spoiler.append({'id': index , 'review' : training_data.iat[index,0]}, ignore_index=True)

In [31]:
rewiev_spoiler_index

0       -1
1       -1
2       -1
3       -1
4       -1
        ..
39995   -1
39996   -1
39997   -1
39998   -1
39999   -1
Name: review, Length: 40000, dtype: int64

In [29]:
#Add a column "Contain_spoiler_word" to the trainin data set 
 
training_data.assign(Cont_Spoiler="")

,review,sentiment,Cont_Spoiler
0,One of the other reviewers has mentioned that ...,positive,
1,A wonderful little production. <br /><br />The...,positive,
2,I thought this was a wonderful way to spend ti...,positive,
3,Basically there's a family where a little boy ...,negative,
4,"Petter Mattei's ""Love in the Time of Money"" is...",positive,
...,...,...,...
39995,This was a marvelously funny comedy with a gre...,positive,
39996,There is no plot. There are no central charact...,positive,
39997,This show is awesome! I love all the actors! I...,positive,
39998,The fact that this movie has been entitled to ...,negative,
39999,I have to confess that I am severely disappoin...,negative,

In [37]:
for index, value in rewiev_spoiler_index.items():
    if value != -1 :
        training_data.iat[index       , 2] = True
    else :
        training_data.iat[index       , 2] = False

In [38]:
training_data

,review,sentiment,Cont_Spoiler
0,One of the other reviewers has mentioned that ...,positive,False
1,A wonderful little production. <br /><br />The...,positive,False
2,I thought this was a wonderful way to spend ti...,positive,False
3,Basically there's a family where a little boy ...,negative,False
4,"Petter Mattei's ""Love in the Time of Money"" is...",positive,False
...,...,...,...
39995,This was a marvelously funny comedy with a gre...,positive,False
39996,There is no plot. There are no central charact...,positive,False
39997,This show is awesome! I love all the actors! I...,positive,False
39998,The fact that this movie has been entitled to ...,negative,False
39999,I have to confess that I am severely disappoin...,negative,False

In [68]:
training_data.iat[422       , 0]

"First and foremost, I loved the novel by Ray Bradbury. It's the kind of horror that gets under your skin and sticks with you later. It was one of his best books, with, you know, Fahrenheit 451 and Dandelion Wine. I as just hoping that this movie would be all right. It had lots of chances, with a great cast, like Jason Robards and Jonathn Pryce. And Bradbury even wrote the script himself. And on top of all that, it has PAM GRIER!<br /><br />How could it fail?<br /><br />There may be spoilers within.<br /><br />First of all, it was dumbed down. Much of the horror from the book was lost as Bradbury must have been forced to keep the violence to a minimum. All the visuals from the book...gone. Everything that made you squirm...gone.<br /><br />And then there's the acting. Like a lot of movies that Disney threw out in the 80s, the kids in this movie cannot act. And, this bugged me a lot, neither of them looked 13 but 9 or 10. Their strong friendship wasn't addressed. It was more like they were acquaintaces. <br /><br />You'd think Jason Robards and Jonathan Pryce could pull this off in their roles of Mr. Halloway and Mr. Dark. But here it's like they just don't care. All they want to do is somehow pay off some mortgage or something. This is far from being some of their best performances. <br /><br />Pam Grier was fine as the witch, but the charecter of the Dust Witch herself wasn't well pulled off. She's a lot less evil and doesn't have the presence as she did in the book. <br /><br />And everything that was left out of the book. The ballon night chase, the marking of Jim's house, the real death of Mr. Dark, what happened to Mr. Coogan on the merry-go-round, the fate of the lightening rod salesman, the real death of the witch, and oh so much more. <br /><br />And the special effects were bad, even for the 80s. The merry-go-round of doom for one thing with the superimposed horses going around wasn't really creepy, and that weird green mist that really had nothing to do with anything. <br /><br />I could keep going about how this movie ripped apart the original novel, but it makes blood boil. Don't see this movie but read the book. It's a classic of Bradbury."

In [41]:
training_data.iat[37973,0]

"I had been interested in this film for a long time, especially after reading a couple of online reviews of the DVD edition; however, I kept postponing its purchase because of the excessive price-tag and utter lack of relevant supplements. When it went out-of-print earlier this year, I finally gave in - but the entire order (which included a number of other highly-desirable titles) got lost in transit!; luckily, the DVD has been re-issued at bargain-price - and I'm sure glad I picked it up! <br /><br />Anyway, this is one strange film, and a genuine sleeper: initially confusing but striking occult tale which manages to hit bullseye with respect to both its forbidding small-town atmosphere and the inherent eeriness of the sinister goings-on. A small cast responds perfectly to a terse, absorbing and intelligent script: lead Strother Martin, in particular, makes the dialogue sound better than it actually is with his nuanced performance as the town doctor/head of the witch's coven; L.Q. Jones and Alvy Moore (both of whom also produced the film!) offer solid support as the no-nonsense sheriff and his comic-strip aficionado assistant.<br /><br />The plot merges elements of various earlier films dealing with witchcraft and the supernatural, and not only the obvious titles: the fact that the town is held under a spell which can't at first be identified, for instance, brings instantly to mind the similar affliction of one specific bourgeois household in Luis Bunuel's sublimely surreal THE EXTERMINATING ANGEL (1962)!; the 'possessed children' angle was borrowed, perhaps, from VILLAGE OF THE DAMNED (1960); there have been many films - especially of a recent vintage - where the satanic rites of a witches' coven are shown: from THE CITY OF THE DEAD (1960) to THE DEVIL RIDES OUT (1968) but, since the proceedings take place in modern-day America (albeit in remote surroundings) and revolve around elderly witches (seeking a 'renaissance'), the film they recall most of all is ROSEMARY'S BABY (1968).<br /><br />The occult scenes (accentuated as much by foggy exteriors as by the shadowy lighting of the garishly-decorated house where the diabolical events take place) are presented in a completely matter-of-fact way as to make them unsettling and extremely effective - particularly the opening sequence involving an army tank crushing a car(!), the rampage of a devil-doll (a concept which has been done to death over the years but, here, it raises an undeniable frisson), a surreal dream sequence (set inside the ice chamber where all the victims are kept, since they can't be buried!), a sequence where the witches attack a doubting member of the coven, a beheading committed by a horse-riding medieval knight(!) and the lengthy 'black mass' finale (with the witches, accompanied by the respective child they will be 'taking over', all dressed in red - except for a black-clad Martin presiding over the ceremony) which culminates in ritual mass suicide! <br /><br />The film also has the guts to deliver a downbeat 'curtain'; it's so refreshing to come across a title (albeit a low-budget production) from a major Hollywood studio, Columbia, that contrives to go so completely against the grain (like, I said, the film is quite weird - extending also to the editing and the score)! It's odd, too, that such a classy - and cinematic - horror offering {sic} should come from a TV director most often associated with Westerns and other family fare! By the way, the same theme was dealt with almost contemporaneously in the nth Christopher Lee/Peter Cushing collaboration NOTHING BUT THE NIGHT (1972; which Lee produced himself!) - a film I foolishly missed out on some 20 years back when it was shown on local TV, and which has been M.I.A. ever since!! <br /><br />P.S. This review of THE BROTHERHOOD OF Satan will certainly contain spoilers but, then, the synopsis and artwork featured on the DVD cover manage to give everything away anyway!"

# Cleaning data

In [42]:
#delete not unique reviews

duplicateRowsDF = training_data[training_data.duplicated()] 

training_data = training_data.drop_duplicates(subset=['review'])

training_data.size

training_data = training_data.drop(['sentiment'], axis=1)

In [44]:
training_data

                                                  review Cont_Spoiler
0      One of the other reviewers has mentioned that ...        False
1      A wonderful little production. <br /><br />The...        False
2      I thought this was a wonderful way to spend ti...        False
3      Basically there's a family where a little boy ...        False
4      Petter Mattei's "Love in the Time of Money" is...        False
...                                                  ...          ...
39995  This was a marvelously funny comedy with a gre...        False
39996  There is no plot. There are no central charact...        False
39997  This show is awesome! I love all the actors! I...        False
39998  The fact that this movie has been entitled to ...        False
39999  I have to confess that I am severely disappoin...        False

[39734 rows x 2 columns]

In [45]:
text = training_data.iat[0,0]
text

"One of the other reviewers has mentioned that after watching just 1 Oz episode you'll be hooked. They are right, as this is exactly what happened with me.<br /><br />The first thing that struck me about Oz was its brutality and unflinching scenes of violence, which set in right from the word GO. Trust me, this is not a show for the faint hearted or timid. This show pulls no punches with regards to drugs, sex or violence. Its is hardcore, in the classic use of the word.<br /><br />It is called OZ as that is the nickname given to the Oswald Maximum Security State Penitentary. It focuses mainly on Emerald City, an experimental section of the prison where all the cells have glass fronts and face inwards, so privacy is not high on the agenda. Em City is home to many..Aryans, Muslims, gangstas, Latinos, Christians, Italians, Irish and more....so scuffles, death stares, dodgy dealings and shady agreements are never far away.<br /><br />I would say the main appeal of the show is due to the fact that it goes where other shows wouldn't dare. Forget pretty pictures painted for mainstream audiences, forget charm, forget romance...OZ doesn't mess around. The first episode I ever saw struck me as so nasty it was surreal, I couldn't say I was ready for it, but as I watched more, I developed a taste for Oz, and got accustomed to the high levels of graphic violence. Not just violence, but injustice (crooked guards who'll be sold out for a nickel, inmates who'll kill on order and get away with it, well mannered, middle class inmates being turned into prison bitches due to their lack of street skills or prison experience) Watching Oz, you may become comfortable with what is uncomfortable viewing....thats if you can get in touch with your darker side."

In [46]:
# Apply a first round of text cleaning techniques
import re
import string
def clean_text_round1(text):
    '''Make text lowercase, remove text in square brackets, remove punctuation and remove words containing numbers.'''
    text = text.lower()
    text = re.sub('\[.*?\]', '', text)
    text = re.sub('[%s]' % re.escape(string.punctuation), '', text)
    text = re.sub('\w*\d\w*', '', text) #delete words that include numbers 
    text = re.sub(" \d+", " ", s) # delete just numbers
    return text


round1 = lambda x: clean_text_round1(x)

In [47]:

training_data_clean = pd.DataFrame(training_data.review.apply(round1))

In [48]:
training_data_clean.iat[0,0]

'one of the other reviewers has mentioned that after watching just  oz episode youll be hooked they are right as this is exactly what happened with mebr br the first thing that struck me about oz was its brutality and unflinching scenes of violence which set in right from the word go trust me this is not a show for the faint hearted or timid this show pulls no punches with regards to drugs sex or violence its is hardcore in the classic use of the wordbr br it is called oz as that is the nickname given to the oswald maximum security state penitentary it focuses mainly on emerald city an experimental section of the prison where all the cells have glass fronts and face inwards so privacy is not high on the agenda em city is home to manyaryans muslims gangstas latinos christians italians irish and moreso scuffles death stares dodgy dealings and shady agreements are never far awaybr br i would say the main appeal of the show is due to the fact that it goes where other shows wouldnt dare forget pretty pictures painted for mainstream audiences forget charm forget romanceoz doesnt mess around the first episode i ever saw struck me as so nasty it was surreal i couldnt say i was ready for it but as i watched more i developed a taste for oz and got accustomed to the high levels of graphic violence not just violence but injustice crooked guards wholl be sold out for a nickel inmates wholl kill on order and get away with it well mannered middle class inmates being turned into prison bitches due to their lack of street skills or prison experience watching oz you may become comfortable with what is uncomfortable viewingthats if you can get in touch with your darker side'

In [49]:
# Apply a second round of cleaning
def clean_text_round2(text):
    '''Get rid of some additional punctuation and non-sensical text that was missed the first time around.'''
    text = re.sub('[‘’“”…]', '', text)
    text = re.sub('\n', '', text)
    return text

round2 = lambda x: clean_text_round2(x)

In [50]:
training_data_clean = pd.DataFrame(training_data_clean.review.apply(round2))

In [51]:
training_data_clean.iat[0,0]

'one of the other reviewers has mentioned that after watching just  oz episode youll be hooked they are right as this is exactly what happened with mebr br the first thing that struck me about oz was its brutality and unflinching scenes of violence which set in right from the word go trust me this is not a show for the faint hearted or timid this show pulls no punches with regards to drugs sex or violence its is hardcore in the classic use of the wordbr br it is called oz as that is the nickname given to the oswald maximum security state penitentary it focuses mainly on emerald city an experimental section of the prison where all the cells have glass fronts and face inwards so privacy is not high on the agenda em city is home to manyaryans muslims gangstas latinos christians italians irish and moreso scuffles death stares dodgy dealings and shady agreements are never far awaybr br i would say the main appeal of the show is due to the fact that it goes where other shows wouldnt dare forget pretty pictures painted for mainstream audiences forget charm forget romanceoz doesnt mess around the first episode i ever saw struck me as so nasty it was surreal i couldnt say i was ready for it but as i watched more i developed a taste for oz and got accustomed to the high levels of graphic violence not just violence but injustice crooked guards wholl be sold out for a nickel inmates wholl kill on order and get away with it well mannered middle class inmates being turned into prison bitches due to their lack of street skills or prison experience watching oz you may become comfortable with what is uncomfortable viewingthats if you can get in touch with your darker side'

In [58]:
training_data_clean.review

0        one of the other reviewers has mentioned that ...
1        a wonderful little production br br the filmin...
2        i thought this was a wonderful way to spend ti...
3        basically theres a family where a little boy j...
4        petter matteis love in the time of money is a ...
                               ...
39995    this was a marvelously funny comedy with a gre...
39996    there is no plot there are no central characte...
39997    this show is awesome i love all the actors it ...
39998    the fact that this movie has been entitled to ...
39999    i have to confess that i am severely disappoin...
Name: review, Length: 39734, dtype: object

# Organizing the data 
USE SPOLIER DATA FRAME BECAUSE OF SIZE

In [64]:
#1 Cleaning spoiler_DF

rewiev_spoiler_clean = pd.DataFrame(rewiev_spoiler.review.apply(round1))
rewiev_spoiler_clean = pd.DataFrame(rewiev_spoiler_clean.review.apply(round2))

In [66]:
rewiev_spoiler_clean

                                                review
0    first and foremost i loved the novel by ray br...
1    very mild spoilers a basic plot outline no rea...
2    this review also contains a spoiler of the fir...
3    first i realize that a  rating is supposed to ...
4    picture the scene where a bunch of scriptwrite...
..                                                 ...
290  its unfortunate that you cant go any lower tha...
291  as some other comments show this movie might s...
292  i get to the cinema every week or so and regul...
293  contains spoilersbr br this movie is utter cra...
294   some spoilers br br this movie is sometimes s...

[295 rows x 1 columns]

In [65]:
from sklearn.feature_extraction.text import CountVectorizer




cv = CountVectorizer(stop_words='english')
data_cv = cv.fit_transform(rewiev_spoiler.review)
data_dtm = pd.DataFrame(data_cv.toarray(), columns=cv.get_feature_names())
data_dtm.index = rewiev_spoiler.index
data_dtm

,00,000,007,02,10,100,100th,101,102,104,...,zinner,zionism,zipper,zombie,zombies,zone,zoo,zoolander,zoom,zoomed
0,0,0,0,0,1,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1,0,0,0,0,0,1,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
290,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
291,0,0,0,0,1,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
292,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
293,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
294,0,0,0,0,1,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [60]:
rewiev_spoiler

        id                                             review
0      422  First and foremost, I loved the novel by Ray B...
1      475  (Very mild spoilers; a basic plot outline, no ...
2      612  This review also contains a spoiler of the fir...
3      691  First, I realize that a "1" rating is supposed...
4      692  Picture the scene where a bunch of scriptwrite...
..     ...                                                ...
290  39652  It's unfortunate that you can't go any lower t...
291  39684  As some other comments show, this movie might ...
292  39726  I get to the cinema every week or so, and regu...
293  39903  ^^contains spoilers^^<br /><br />This movie is...
294  39916  * Some spoilers *<br /><br />This movie is som...

[295 rows x 2 columns]

In [ ]:
# MATRIX NOT WORKING

In [56]:

from sklearn.feature_extraction.text import CountVectorizer

cv = CountVectorizer(stop_words='english')
data_cv = cv.fit_transform(training_data_clean.review)
 
data_dtm = pd.DataFrame(training_data_clean['review'].tolist(), columns=cv.get_feature_names())
data_dtm.index = training_data_clean.index
data_dtm


data_dtm = data_dtm.transpose()

 
top_dict = {}
for c in data_dtm.columns:
    top = data_dtm[c].sort_values(ascending=False).head(30)
    top_dict[c]= list(zip(top.index, top.values))

top_dict

ValueError: Shape of passed values is (39734, 1), indices imply (39734, 154351)

In [53]:
training_data_clean

                                                  review
0      one of the other reviewers has mentioned that ...
1      a wonderful little production br br the filmin...
2      i thought this was a wonderful way to spend ti...
3      basically theres a family where a little boy j...
4      petter matteis love in the time of money is a ...
...                                                  ...
39995  this was a marvelously funny comedy with a gre...
39996  there is no plot there are no central characte...
39997  this show is awesome i love all the actors it ...
39998  the fact that this movie has been entitled to ...
39999  i have to confess that i am severely disappoin...

[39734 rows x 1 columns]

top_dict