In [1]:
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.cluster import KMeans
import numpy as np
import pandas as pd
from time import time
from sklearn.feature_extraction.text import TfidfVectorizer, CountVectorizer
from sklearn.naive_bayes import MultinomialNB
from sklearn import metrics
import matplotlib.pylab as plt
import scipy.sparse as sparse

In [ ]:
#pip install --user  lazypredict

In [2]:
data = pd.read_csv('cleaned_data.csv') # load cleaned data
data["sentiment_int"]=data["sentiment"].replace("positive", 1).replace("negative",0)
data.head()

,review,sentiment,lemmatization,stemming,sentiment_int
0,one reviewers mentioned watching oz episode yo...,positive,one reviewer mentioned watching oz episode you...,one review mention watch oz episod youll hook ...,1
1,wonderful little production filming technique ...,positive,wonderful little production filming technique ...,wonder littl product film techniqu unassum old...,1
2,thought wonderful way spend time hot summer we...,positive,thought wonderful way spend time hot summer we...,thought wonder way spend time hot summer weeke...,1
3,basically theres family little boy jake thinks...,negative,basically there family little boy jake think t...,basic there famili littl boy jake think there ...,0
4,petter matteis love time money visually stunni...,positive,petter matteis love time money visually stunni...,petter mattei love time money visual stun film...,1

In [3]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(data['lemmatization'], data["sentiment_int"], train_size = 0.75)

In [4]:
tf_vectorizer = TfidfVectorizer(stop_words='english', min_df=5, max_df=0.3) # create Object of class TfidfVectorizer

X_train_tf = tf_vectorizer.fit_transform(X_train) # run method fit_transform on training set

print("n_samples: %d, n_features: %d" % X_train_tf.shape)

n_samples: 37500, n_features: 30915

In [5]:
#X_train_tr=X_train_tf.transpose()
X_train_df = pd.DataFrame(X_train_tf.toarray(),columns=tf_vectorizer.get_feature_names())
X_train_df

,aa,aaa,aag,aaliyah,aames,aamir,aardman,aaron,ab,aback,...,zu,zucco,zuccos,zucker,zudina,zulu,zuniga,zurer,zwick,émigré
0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
37495,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
37496,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
37497,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
37498,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
37499,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [ ]:
#pip install pyspellchecker

In [7]:
X_test_tf = tf_vectorizer.fit_transform(X_test) # run method fit_transform on training set
X_test_df = pd.DataFrame(X_test_tf.toarray(),columns=tf_vectorizer.get_feature_names())
X_test_df

,aamir,aaron,abandon,abandoned,abandoning,abandonment,abba,abbas,abbey,abbot,...,zoey,zombie,zombified,zone,zoo,zoom,zooming,zorro,zu,zucker
0,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,...,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00
1,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,...,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00
2,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,...,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00
3,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,...,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00
4,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,...,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
12495,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,...,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00
12496,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,...,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00
12497,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,...,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00
12498,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,...,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00
12499,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,...,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00

TypeError: 'Index' object is not callable

In [ ]:

plt.figure(figsize=(15, 15))
plt.spy(X_train_tf, markersize=0.005)

In [6]:
from lazypredict.Supervised import LazyClassifier

C:\Users\jibiz\AppData\Roaming\Python\Python38\site-packages\sklearn\utils\deprecation.py:143: FutureWarning: The sklearn.utils.testing module is  deprecated in version 0.22 and will be removed in version 0.24. The corresponding classes / functions should instead be imported from sklearn.utils. Anything that cannot be imported from sklearn.utils is now part of the private API.
  warnings.warn(message, FutureWarning)

In [8]:
clf = LazyClassifier(verbose=0, ignore_warnings=True)
models, predictions = clf.fit(X_train_df, X_test_df, y_train, y_test)
models

100%|██████████| 29/29 [2:16:16<00:00, 281.96s/it]

Empty DataFrame
Columns: [Accuracy, Balanced Accuracy, ROC AUC, F1 Score, Time Taken]
Index: []

Empty DataFrame
Columns: [Accuracy, Balanced Accuracy, ROC AUC, F1 Score, Time Taken]
Index: []